package io.dacopancm.jfee.sp.model;
// Generated 28/11/2015 13:30:26 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.management.relation.Role;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "usr_id", unique = true, nullable = false)
    private int usrId;
    @Column(name = "usr_ci", length = 45)
    private String usrCi;
    @Column(name = "usr_password", length = 45)
    private String usrPassword;
    @Column(name = "usr_email", length = 45)
    private String usrEmail;
    @Column(name = "usr_active")
    private Boolean usrActive;
    @Column(name = "usr_failed_login")
    private Integer usrFailedLogin;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "usr_creation_timestamp", length = 19)
    private Date usrCreationTimestamp;
    @Column(name = "usr_last_failed_login")
    @Temporal(TemporalType.TIMESTAMP)
    private Date usrLastFailedLogin;
    @Size(max = 45)
    @Column(name = "usr_activation_hash")
    private String usrActivationHash;
    @Size(max = 45)
    @Column(name = "usr_password_reset_hash")
    private String usrPasswordResetHash;
    @OneToOne(fetch = FetchType.LAZY)
    @JoinTable(name = "ROL_MIEMBRO",
            joinColumns = {
                @JoinColumn(name = "usr_id", referencedColumnName = "usr_id")},
            inverseJoinColumns = {
                @JoinColumn(name = "rol_id", referencedColumnName = "rol_id")}
    )
    private Rol rol;

    public Usuario() {
    }

    public Usuario(int usrId, String usrCi, String usrPassword, String usrEmail, Boolean usrActive, Integer usrFailedLogin, Date usrCreationTimestamp, Date usrLastFailedLogin, String usrActivationHash, String usrPasswordResetHash, Rol rol) {
        this.usrId = usrId;
        this.usrCi = usrCi;
        this.usrPassword = usrPassword;
        this.usrEmail = usrEmail;
        this.usrActive = usrActive;
        this.usrFailedLogin = usrFailedLogin;
        this.usrCreationTimestamp = usrCreationTimestamp;
        this.usrLastFailedLogin = usrLastFailedLogin;
        this.usrActivationHash = usrActivationHash;
        this.usrPasswordResetHash = usrPasswordResetHash;
        this.rol = rol;
    }

    public int getUsrId() {
        return usrId;
    }

    public void setUsrId(int usrId) {
        this.usrId = usrId;
    }

    public String getUsrCi() {
        return usrCi;
    }

    public void setUsrCi(String usrCi) {
        this.usrCi = usrCi;
    }

    public String getUsrPassword() {
        return usrPassword;
    }

    public void setUsrPassword(String usrPassword) {
        this.usrPassword = usrPassword;
    }

    public String getUsrEmail() {
        return usrEmail;
    }

    public void setUsrEmail(String usrEmail) {
        this.usrEmail = usrEmail;
    }

    public Boolean getUsrActive() {
        return usrActive;
    }

    public void setUsrActive(boolean usrActive) {
        this.usrActive = usrActive;
    }

    public Integer getUsrFailedLogin() {
        return usrFailedLogin;
    }

    public void setUsrFailedLogin(Integer usrFailedLogin) {
        this.usrFailedLogin = usrFailedLogin;
    }

    public Date getUsrCreationTimestamp() {
        return usrCreationTimestamp;
    }

    public void setUsrCreationTimestamp(Date usrCreationTimestamp) {
        this.usrCreationTimestamp = usrCreationTimestamp;
    }

    public Date getUsrLastFailedLogin() {
        return usrLastFailedLogin;
    }

    public void setUsrLastFailedLogin(Date usrLastFailedLogin) {
        this.usrLastFailedLogin = usrLastFailedLogin;
    }

    public String getUsrActivationHash() {
        return usrActivationHash;
    }

    public void setUsrActivationHash(String usrActivationHash) {
        this.usrActivationHash = usrActivationHash;
    }

    public String getUsrPasswordResetHash() {
        return usrPasswordResetHash;
    }

    public void setUsrPasswordResetHash(String usrPasswordResetHash) {
        this.usrPasswordResetHash = usrPasswordResetHash;
    }

    public Rol getRol() {
        return rol;
    }

    public void setRole(Rol role) {
        this.rol = role;
    }

}
