#!/bin/bash
echo "PRE_BUILD action hooks execute START"
pwd

# clean repo
rm -rf $OPENSHIFT_HOMEDIR/app-root/repo/deployments
#rm -rf $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-ear/target
#rm -rf $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-ejb/target
rm -rf $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-web/target
rm -rf $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-web/deployments

# clean deploy
rm -rf $OPENSHIFT_HOMEDIR/app-deployments/current/repo/deployments
#rm -rf $OPENSHIFT_HOMEDIR/app-deployments/current/repo/javafutbolee-ear/target
#rm -rf $OPENSHIFT_HOMEDIR/app-deployments/current/repo/javafutbolee-ejb/target
rm -rf $OPENSHIFT_HOMEDIR/app-deployments/current/repo/javafutbolee-web/target
rm -rf $OPENSHIFT_HOMEDIR/app-deployments/current/repo/javafutbolee-web/deployments

echo "PRE_BUILD DOWNLOAD resources START"
curl -L -o $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-web/src/main/webapp/resources/resources1.tar.gz https://www.dropbox.com/s/qumz51q04u9ncuw/resources1.tar.gz?dl=1
curl -L -o $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-web/src/main/webapp/resources/resources2.tar.gz https://www.dropbox.com/s/dfezes4tdn9bh8k/resources2.tar.gz?dl=1
tar -zxvf $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-web/src/main/webapp/resources/resources1.tar.gz -C $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-web/src/main/webapp/resources/
tar -zxvf $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-web/src/main/webapp/resources/resources2.tar.gz -C $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-web/src/main/webapp/resources/
mv $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-web/src/main/webapp/resources/resources/email $OPENSHIFT_HOMEDIR/app-root/repo/javafutbolee-web/src/main/resources/email
echo "PRE_BUILD DOWNLOAD resources END"


echo "PRE_BUILD action hooks execute END"


