package io.dacopancm.jfee.sp.model;
// Generated 28/11/2015 13:30:26 by Hibernate Tools 4.3.1

import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "jfee", uniqueConstraints = @UniqueConstraint(columnNames = "rol_nombre")
)
public class Rol implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "rol_id", unique = true, nullable = false)
    private Integer rolId;

    @Column(name = "rol_nombre", unique = true, nullable = false, length = 45)
    private String rolNombre;
    @OneToMany(cascade = CascadeType.ALL)
    @JoinTable(name = "ROL_MIEMBRO",
            joinColumns = {
                @JoinColumn(name = "rol_id", referencedColumnName = "rol_id")},
            inverseJoinColumns = {
                @JoinColumn(name = "usr_id", referencedColumnName = "usr_id")}
    )
    private Set<Usuario> userRoles;

    public Rol() {
    }

    public Rol(Integer rolId, String rolNombre, Set<Usuario> userRoles) {
        this.rolId = rolId;
        this.rolNombre = rolNombre;
        this.userRoles = userRoles;
    }

    public Integer getRolId() {
        return rolId;
    }

    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }

    public String getRolNombre() {
        return rolNombre;
    }

    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }

    public Set<Usuario> getUserRoles() {
        return userRoles;
    }

    public void setUserRoles(Set<Usuario> userRoles) {
        this.userRoles = userRoles;
    }

}
